[endpoints]
acala = [
  "wss://acala-polkadot.api.onfinality.io/public-ws"
]
polkadot = [
  "wss://polkadot.api.onfinality.io/public-ws"
]

[strategy]
atList = [100000000, 200000000, 300000000]
interval = 1000
remained = 1

[account]
receive= "5GREeQcGHt7na341Py6Y6Grr38KUYRvVoiFSiDB52Gt7VZiN"
signer = "YOUR MNEMONIC"
