[endpoints]
acala = [
  "wss://karura.api.onfinality.io/public-ws"
]
polkadot = [
  "wss://kusama.api.onfinality.io/public-ws"
]

[strategy]
atList = [12450960, 13000000, 14000000]
interval = 1000
remained = 1

[account]
receive= "5CdF5f5YtcA52d9K6dAbvkR3hk5tKuoBFAhiWf47GggaBMPH"
signer = "YOUR MNEMONIC"
